CREATE TABLE EMPRESA
(
  K_EMPRESA NUMERIC(3, 0) NOT NULL 
, N_NOMEMPRE VARCHAR(50) NOT NULL 
, O_DIREMPRE VARCHAR(100) NOT NULL 
, O_TELEMPRE NUMERIC(10, 0) NOT NULL 
, CONSTRAINT EMPRESA_PK PRIMARY KEY 
  (
    K_EMPRESA 
  )
);

CREATE TABLE CLI_FAMISANAR 
(
  K_NUMIDEN NUMERIC(12, 0) NOT NULL 
, N_NOMBRE VARCHAR(20) NOT NULL 
, N_APELLIDO VARCHAR(20) NOT NULL 
, F_NACIMIENTO DATE NOT NULL 
, F_AFILIACION DATE 
, I_TIPO VARCHAR(1) NOT NULL 
, I_SEXO VARCHAR(1) NOT NULL 
, I_ESTADO VARCHAR(1) NOT NULL 
, V_SUELDO NUMERIC(10, 2) 
);

CREATE TABLE CLI_COMPENSAR 
(
  K_NUMIDEN NUMERIC(12, 0) NOT NULL 
, K_EMPRESA NUMERIC(3, 0)
, N_NOMBRE VARCHAR(20) NOT NULL 
, N_APELLIDO VARCHAR(20) NOT NULL 
, F_NACIMIENTO DATE NOT NULL 
, I_TIPO VARCHAR(1) NOT NULL 
, I_SEXO VARCHAR(1) NOT NULL 
, I_ESTADO VARCHAR(1) NOT NULL
, CONSTRAINT CLI_COMPENSAR_PK PRIMARY KEY 
  (
    K_NUMIDEN 
  )
);

ALTER TABLE CLI_COMPENSAR
ADD CONSTRAINT CLI_COMPENSAR_EMPRESA_FK FOREIGN KEY
(
  K_EMPRESA 
)
REFERENCES EMPRESA
(
  K_EMPRESA 
);
